### ISSUE TITLE
重生時破圖

### ISSUE THREAD

**Issue by STEVE1010101** [Imanity-Software/ImanitySpigot3-git#103]
### Expected behavior 預期狀況

玩家重生時應該要正常

### Observed/Actual behavior 實際狀況

玩家破圖卡住

### Steps/models to reproduce 重現的方式

![image](https://user-images.githubusercontent.com/70594985/163992240-78330d1d-004a-4615-b1a3-7cd511b322ad.png)

### Plugin list 插件列表

![image](https://user-images.githubusercontent.com/70594985/163992367-5ff8373d-afbe-49d6-b423-73cc3c5de35e.png)

```
### ImanitySpigot3 的版本

# -------------------------------------------------------
# Imanity Software © 2019 ~ 2021
#  
# Welcome to the Rancha configuration of ImanitySpigot3! (rancha.yml)
# If you need help with the configuration or have any question related to ImanitySpigot,
# join our discord. Happy Configuration!
#  
# Discord: https://discord.gg/GBZKR3nn
# -------------------------------------------------------

# The path for License Key File
# By this option you can set it to a static location
# Which allowing you to using same license key file across the machine.
licenseKeyFilePath: imanity/.license

# Dependencies version controlThis area provides the ability to upgrade the dependency to a more recent versions
# Upgrade dependency allow you to access modern features and minor performance improvement
# However, it may happen that the plugins is not supported
# Please consider it before upgrading.
dependencies:

  # The Google Json Library
  # LEGACY -> 2.2.4 (MC1.8)
  # MODERN -> 2.8.7
  gson: LEGACY

  # The MySql Connector Driver Library
  # LEGACY -> 5.1.14 (MC1.8)
  # MODERN -> 8.0.25
  mysqlDriver: LEGACY

  # The Netty Library
  # LEGACY -> 4.0.23.Final (MC1.8)
  # MODERN -> 4.1.60.Final
  #  
  # IMPORTANT NOTE: To run ImanitySpigot3 for java 9+, Netty will be forced to be modern.
  netty: LEGACY

# The amount of threads to download Spigot JAR
# Bumping download thread count could provide higher download speed
downloadThreads: 1

# Automated Update system
# This area provides the ability to keep your spigot JAR up to date by automatically download updates.
automated:

  # Automatically update to latest build of your current release when new build were detected
  updateToLatestBuild: true

  # Automatically update to latest LTS release when new LTS version were detected
  # This is not recommended if you care about stability
  # Since each LTS version could have potential changes.
  updateToLatestLTS: false

  # Automatically update to latest release when new version were detected
  # This is very NOT recommended
  # It will update to whatever version, Including LTS or non-LTS
  updateToLatestVersion: false

# The current version of ImanitySpigot3
# DO NOT TOUCH IT IF YOU DON'T KNOW WHAT YOU ARE USING
spigotJarVersion: 2021.10.1 BUILD 12

# The scheduled updated version of ImanitySpigot3
# DO NOT TOUCH IT IF YOU DON'T KNOW WHAT YOU ARE USING
scheduledUpdateVersion: none

# ImanitySpigot3 has updated Netty to the latest version
# But it also comes with come incompatible issues with plugins
# Since in older versions, netty usually copies bytes to heap buffer with allows you to read byte array
# But in newer versions, It will return direct buffer instead
# So this option patch netty to use heap unpooled buffer, So it could fix the issue
forceNettyUseUnpoolBuffer: true
```

### Agreements 同意事項

- [x] 我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

### Others 額外資訊

玩家在"/setworldspawn"的範圍外重生就會破圖
以前的版本ispigot沒有這問題 (不確定哪個版本)
