### ISSUE TITLE
Emerald generation does not replace the vanilla generation in mountains biome

### ISSUE THREAD

**Issue by VadamDev** [Imanity-Software/ImanitySpigot3-git#176]
### Expected behavior

customBlockRuleSet should override vanilla emerald generation in mountains

![2023-01-27_08 24 09](https://user-images.githubusercontent.com/47008488/215030960-8637e580-69d7-4e65-9088-faa23506cfb0.png)

### Observed/Actual behavior

![Sans titre](https://user-images.githubusercontent.com/47008488/215030740-4b5c9762-b990-4dd0-bd71-54ba7f5fc2f0.png)

The custom generation is mixed with the vanilla generation

### Steps/models to reproduce

- Make sure the moutains biome generation is enabled

Add this to the customBlockRuleSet:
```
- blockData:
      material: EMERALD_ORE
      data: 0
    toReplace: STONE
    veinGenerateRate: 100.0
    maxSizePerVein: 4
    veinsPerChunk: 1
    minHeight: 0
    maxHeight: 16
```
Regenerate the world an go to a mountains biome and dig

### Plugin list

![image](https://user-images.githubusercontent.com/47008488/215026168-104bc10c-d5af-43be-bc05-abde905e2ecc.png)

### ImanitySpigot3 version

2022.11.1 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

The ores on the screenshot is an emerald ore but with a custom texture.
