### ISSUE TITLE
Remove lake & remove rivers flags does not remove lakes generated by heightmap

### ISSUE THREAD

**Issue by louseee** [Imanity-Software/ImanitySpigot3-git#180]
### Expected behavior

I expected the flags "removeRivers" and "removeLakes" to remove all lakes and rivers within the radius I provided. However, it doesn't seem to be working correctly.

### Observed/Actual behavior

Here is an example of what I got when generating a map with the flags.

https://imgur.com/MEusF8D
https://imgur.com/yhoLp0b

### Steps/models to reproduce

I used the following configuration to try to remove the rivers and lakes.

```
regions:
- enabled: true
  x: 0
  z: 0
  range: 400
  modifications:
  - type: biome
    biome: ROOFED_FOREST
  - type: removeRivers
  - type: removeLakes
    removeWaterLakes: true
    removeLavaLakes: true
```

### Plugin list

None.

### ImanitySpigot3 version

2023.02.1 LTS BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.
